[Service]
NoNewPrivileges=yes
PrivateTmp=yes
ProtectKernelTunables=yes
ProtectKernelModules=yes
ProtectKernelLogs=yes
ProtectHostname=yes
RestrictSUIDSGID=yes
LockPersonality=yes
RestrictNamespaces=yes
ProtectProc=invisible
ProcSubset=pid
RestrictRealtime=yes
ProtectControlGroups=yes
RestrictAddressFamilies=AF_UNIX AF_INET AF_INET6
UMask=0077
TemporaryFileSystem=/tmp:rw,noexec,nosuid,nodev,mode=1777
TemporaryFileSystem=/var/tmp:rw,noexec,nosuid,nodev,mode=1777
