#ifndef TA_HESIA_H
#define TA_HESIA_H

#define TA_HESIA_UUID \
    { 0xa17de805, 0x9dc1, 0x43ef, \
      { 0x93, 0x2b, 0x91, 0xf1, 0x07, 0xca, 0xd5, 0x7b } }

#define TA_HESIA_CMD_SEAL         0x0001
#define TA_HESIA_CMD_UNSEAL       0x0002
#define TA_HESIA_CMD_ROTATE_KEY   0x0003
#define TA_HESIA_CMD_WIPE_KEY     0x0004
#define TA_HESIA_CMD_HKDF         0x0005
#define TA_HESIA_CMD_CHECK_VERSION 0x0006
#define TA_HESIA_CMD_RESET_VERSION 0x0007
#define TA_HESIA_CMD_READ_VERSION  0x0008
#define TA_HESIA_CMD_EXPORT_ATTEST_PUBKEY 0x0009
#define TA_HESIA_CMD_SIGN_ATTEST_DIGEST   0x000A
#define TA_HESIA_CMD_SET_SESSION_AUTH_SECRET 0x000B
#define TA_HESIA_CMD_STAGE_SLOT_UPDATE    0x000C
#define TA_HESIA_CMD_COMMIT_SLOT_BOOT     0x000D
#define TA_HESIA_CMD_READ_SLOT_META       0x000E
#define TA_HESIA_CMD_GET_RECOVERY_CHALLENGE 0x000F
#define TA_HESIA_CMD_RECOVER_SESSION_AUTH   0x0010
#define TA_HESIA_CMD_IMPORT_MLDSA_KEY_BLOB  0x0011
#define TA_HESIA_CMD_EXPORT_MLDSA_PUBKEY    0x0012
#define TA_HESIA_CMD_SIGN_MLDSA_PAYLOAD     0x0013
#define TA_HESIA_CMD_GET_MLDSA_STATUS       0x0014
#define TA_HESIA_CMD_GENERATE_MLDSA_KEYPAIR 0x0015

#define HESIA_MLDSA_SLOT_DRONE  0u
#define HESIA_MLDSA_SLOT_SERVER 1u

#define HESIA_MLDSA_IMPORT_STAGE_INIT             0u
#define HESIA_MLDSA_IMPORT_STAGE_ALLOC            1u
#define HESIA_MLDSA_IMPORT_STAGE_UNSEAL           2u
#define HESIA_MLDSA_IMPORT_STAGE_PARSE            3u
#define HESIA_MLDSA_IMPORT_STAGE_BACKEND_READY    4u
#define HESIA_MLDSA_IMPORT_STAGE_SELFTEST_SIGN    5u
#define HESIA_MLDSA_IMPORT_STAGE_SELFTEST_VERIFY  6u
#define HESIA_MLDSA_IMPORT_STAGE_PERSIST          7u
#define HESIA_MLDSA_IMPORT_STAGE_DONE             8u

#define HESIA_MLDSA_KEYGEN_STAGE_INIT       0u
#define HESIA_MLDSA_KEYGEN_STAGE_ALLOC      1u
#define HESIA_MLDSA_KEYGEN_STAGE_GENERATE   2u
#define HESIA_MLDSA_KEYGEN_STAGE_SERIALIZE  3u
#define HESIA_MLDSA_KEYGEN_STAGE_PERSIST    4u
#define HESIA_MLDSA_KEYGEN_STAGE_DONE       5u

#define HESIA_RECOVERY_MAGIC   0x48535231u
#define HESIA_RECOVERY_VERSION 2u
#define HESIA_RECOVERY_NONCE_LEN 32
#define HESIA_RECOVERY_ATTEST_PUBKEY_LEN 65
#define HESIA_RECOVERY_SIG_LEN 64
#define HESIA_RECOVERY_TTL_SEC 300u

typedef struct {
    uint32_t magic;
    uint32_t version;
    uint64_t expires_at_sec;
    uint8_t nonce[HESIA_RECOVERY_NONCE_LEN];
    uint8_t attest_pubkey[HESIA_RECOVERY_ATTEST_PUBKEY_LEN];
} hesia_recovery_challenge_t;

typedef struct {
    uint32_t magic;
    uint32_t version;
    uint64_t expires_at_sec;
    uint8_t nonce[HESIA_RECOVERY_NONCE_LEN];
    uint8_t new_secret_hash[32];
    uint8_t attest_pubkey_hash[32];
    uint8_t signature[HESIA_RECOVERY_SIG_LEN];
} hesia_recovery_token_t;

#endif /* TA_HESIA_H */
